version: "3.9"

services:
  worker-service:
    build: ./worker-service
    ports:
      - "3001:3001"

  api-service:
    build: ./api-service
    ports:
      - "3000:3000"
    depends_on:
      - worker-service

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api-service
      - worker-service

