global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-service"
    static_configs:
      - targets: ["api-service:3000"]

  - job_name: "worker-service"
    static_configs:
      - targets: ["worker-service:3001"]
